### ISSUE TITLE
Step is switching to default branch after adding a tag

### ISSUE THREAD

**Issue by aachojnacki** [ned1988/bitrise-step-git-tag-project-version-and-build-number#16]
I don't think that's necessary. This messed up my workflow because the default branch was set to dev while I wanted to build from whichever branch the job was triggered from... Had to set the default branch to "--"

**Comment by denys-meloshyn** [comment]
If I'm not wrong to add the `tag` I need firstly `checkout` the branch from which the build was triggered, because at this moment git has detached head. I can try to check if it possible to tag commit instead of branch
Is it possible for you to move it as a last step?

Edit
Actually I'm already attaching tag to commit, I'll try to remove the checkout and see what happens

**Comment by aachojnacki** [comment]
If I’m not mistaken the checkout is done _after_ the tag has been added and pushed to repository. Seems unnecessary. But adding it as a last step would definitely do the trick (because the last checkout wouldn’t contribute to the build), it’s not perfect for my workflow though.

**Comment by denys-meloshyn** [comment]
Can you please try to update your `yml` file ([example](https://github.com/bitrise-io/bitrise-steplib/pull/2206#issuecomment-547377175)) and use `avoid-checkout` branch instead of release version, if it works I create a new release soon.

**Comment by aachojnacki** [comment]
Yup, this solves it for me

**Comment by denys-meloshyn** [comment]
Cool, in this case I'll start a new release👍
